[package]
name = "celo-client"
version = "0.1.0"
publish = false
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# Workspace
alloy-celo-evm.workspace = true
celo-proof.workspace = true
celo-driver.workspace = true
celo-genesis = { workspace = true, features = ["serde"] }
celo-protocol.workspace = true

# Kona
kona-client.workspace = true

# Proof
kona-preimage.workspace = true
kona-executor.workspace = true
kona-proof.workspace = true
kona-std-fpvm.workspace = true
kona-std-fpvm-proc.workspace = true

# Protocol
kona-derive.workspace = true

# Alloy
alloy-consensus.workspace = true
alloy-primitives.workspace = true

# Hokulea - temporarily commented out for Step 1 (kona upgrade)
# hokulea-eigenda.workspace = true
# hokulea-proof.workspace = true

# General
cfg-if.workspace = true
tracing.workspace = true

[dev-dependencies]
kona-preimage = { workspace = true, features = ["std"] }

[features]
default = ["client-tracing"]
client-tracing = ["kona-std-fpvm/tracing"]

[[bin]]
name = "celo-client"
path = "src/client.rs"
