name: Proof
on:
  push:
    tags:
      - celo/v[0-9]*
    branches: [main]
  merge_group:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

env:
  CARGO_TERM_COLOR: always

jobs:
  host-client-offline-runs:
    name: FPP e2e - ${{ matrix.target}} | ${{ matrix.name }}
    strategy:
      matrix:
        target: ["native"]
        name: ["Celo Sepolia (Jovian) - Block #34620000"]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
      - uses: ./.github/actions/setup
        with:
          components: llvm-tools-preview
          prefix-key: ${{ matrix.target }}-${{ matrix.name }}
      - uses: taiki-e/install-action@cargo-llvm-cov
      # Below variables can be retrieved by running `just run-client-native`, and witness tar file can be created by compressing the generated data directory after running the command.
      - name: Set run environment
        run: |
          if [[ ${{ contains(matrix.name, 34620000) }} == true ]]; then
            BLOCK_NUMBER=34620000
            echo "BLOCK_NUMBER=$BLOCK_NUMBER" >> $GITHUB_ENV
            echo "L2_CLAIM=0xc95dc2a8a13b7c9b39636f03e35845532a18731ab57b310d14f63a34eaf6ed8e" >> $GITHUB_ENV
            echo "L2_OUTPUT_ROOT=0xb509703c2128aef5676d53be90302a8c70d30f8b6691af1a8037e68a08911998" >> $GITHUB_ENV
            echo "L2_HEAD=0x47cbe839a86d0b34c797438502d44d17caac2181c1b247d76b655d17b1324ed1" >> $GITHUB_ENV
            echo "L1_HEAD=0xcc7997034fe84bc29d17f2556e33fbc6f6b72b28fbdb86640ce6adac0e347dcd" >> $GITHUB_ENV
            echo "L2_CHAIN_ID=11142220" >> $GITHUB_ENV
            echo "WITNESS_TAR_NAME=jovian-celo-sepolia-$BLOCK_NUMBER-witness.tar.zst" >> $GITHUB_ENV
          fi
      - name: Decompress witness data directory
        run: |
          tar --zstd -xvf ./bin/client/testdata/$WITNESS_TAR_NAME -C .
      - name: Run host + client offline
        working-directory: ./bin/client
        run: |
          mkdir -p ../../target
          just run-client-${{ matrix.target }}-offline \
            $BLOCK_NUMBER \
            $L2_CLAIM \
            $L2_OUTPUT_ROOT \
            $L2_HEAD \
            $L1_HEAD \
            $L2_CHAIN_ID
