name: Push container images for development

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - celo/v[0-9]*
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

jobs:
  push_container_dev:
    name: Build and push celo-kona development image
    uses: ./.github/workflows/push-container.yaml
    with:
      file: Dockerfile
      artifact-registry: us-west1-docker.pkg.dev/devopsre/dev-images/${{ github.event.repository.name }}
      service-account: celo-kona-gh@devopsre.iam.gserviceaccount.com
      workload-id-provider: projects/1094498259535/locations/global/workloadIdentityPools/gh-celo-kona/providers/github-by-repos
      concurrency-group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
